///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomationTestProject.Recording
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Goto_GiaoBaiTap_button recording.
    /// </summary>
    [TestModule("0ef1f017-47c7-49ec-9cf2-84f8fadee4d4", ModuleType.Recording, 1)]
    public partial class Goto_GiaoBaiTap_button : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutomationTestProject.AutomationTestProjectRepository repository.
        /// </summary>
        public static AutomationTestProject.AutomationTestProjectRepository repo = AutomationTestProject.AutomationTestProjectRepository.Instance;

        static Goto_GiaoBaiTap_button instance = new Goto_GiaoBaiTap_button();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Goto_GiaoBaiTap_button()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Goto_GiaoBaiTap_button Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.Lớp6' at 47;24.", repo.HọcLiệuSachMềm.Lớp6Info, new RecordItemIndex(0));
            repo.HọcLiệuSachMềm.Lớp6.Click("47;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.TiếngAnh6Tập1SachBaiTập' at 178;23.", repo.HọcLiệuSachMềm.TiếngAnh6Tập1SachBaiTậpInfo, new RecordItemIndex(1));
            repo.HọcLiệuSachMềm.TiếngAnh6Tập1SachBaiTập.Click("178;23");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.giaobaitap' at Center.", repo.HọcLiệuSachMềm.giaobaitapInfo, new RecordItemIndex(2));
            repo.HọcLiệuSachMềm.giaobaitap.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
