///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomationTestProject.Recording
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("7bf868ca-78a7-4834-b32d-6d53fae6ddef", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutomationTestProject.AutomationTestProjectRepository repository.
        /// </summary>
        public static AutomationTestProject.AutomationTestProjectRepository repo = AutomationTestProject.AutomationTestProjectRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HọcLiệuSachMềm.LinkLogin' at Center.", repo.HọcLiệuSachMềm.LinkLoginInfo, new RecordItemIndex(0));
            repo.HọcLiệuSachMềm.LinkLogin.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s for the attribute 'Visible' to equal the specified value 'True'. Associated repository item: 'ĐăngNhậpSachMềm'", repo.ĐăngNhậpSachMềm.SelfInfo, new RecordItemIndex(1));
            repo.ĐăngNhậpSachMềm.SelfInfo.WaitForAttributeEqual(5000, "Visible", "True");
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to 'about.nguyenthang@gmail.com' on item 'ĐăngNhậpSachMềm.Body.Email'.", repo.ĐăngNhậpSachMềm.Body.EmailInfo, new RecordItemIndex(2));
            repo.ĐăngNhậpSachMềm.Body.Email.Element.SetAttributeValue("Value", "about.nguyenthang@gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '03121998' on item 'ĐăngNhậpSachMềm.Body.Password'.", repo.ĐăngNhậpSachMềm.Body.PasswordInfo, new RecordItemIndex(3));
            repo.ĐăngNhậpSachMềm.Body.Password.Element.SetAttributeValue("Value", "03121998");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ĐăngNhậpSachMềm.Body.Commit' at Center.", repo.ĐăngNhậpSachMềm.Body.CommitInfo, new RecordItemIndex(4));
            repo.ĐăngNhậpSachMềm.Body.Commit.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
