///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutomationTestProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("b1b7a2de-ea18-4bc1-a583-7397b33901d4")]
    public partial class AutomationTestProjectRepository : RepoGenBaseFolder
    {
        static AutomationTestProjectRepository instance = new AutomationTestProjectRepository();
        AutomationTestProjectRepositoryFolders.HọcLiệuSachMềmAppFolder _họcliệusachmềm;
        AutomationTestProjectRepositoryFolders.ĐăngNhậpSachMềmAppFolder _đăngnhậpsachmềm;

        /// <summary>
        /// Gets the singleton class instance representing the AutomationTestProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("b1b7a2de-ea18-4bc1-a583-7397b33901d4")]
        public static AutomationTestProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutomationTestProjectRepository() 
            : base("AutomationTestProjectRepository", "/", null, 0, false, "b1b7a2de-ea18-4bc1-a583-7397b33901d4", ".\\RepositoryImages\\AutomationTestProjectRepositoryb1b7a2de.rximgres")
        {
            _họcliệusachmềm = new AutomationTestProjectRepositoryFolders.HọcLiệuSachMềmAppFolder(this);
            _đăngnhậpsachmềm = new AutomationTestProjectRepositoryFolders.ĐăngNhậpSachMềmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b1b7a2de-ea18-4bc1-a583-7397b33901d4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềm folder.
        /// </summary>
        [RepositoryFolder("824fbfaa-15d7-4bfd-9f08-6d137806f73a")]
        public virtual AutomationTestProjectRepositoryFolders.HọcLiệuSachMềmAppFolder HọcLiệuSachMềm
        {
            get { return _họcliệusachmềm; }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềm folder.
        /// </summary>
        [RepositoryFolder("7ee862ee-d4ef-4165-b63a-15aaab7bcaad")]
        public virtual AutomationTestProjectRepositoryFolders.ĐăngNhậpSachMềmAppFolder ĐăngNhậpSachMềm
        {
            get { return _đăngnhậpsachmềm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class AutomationTestProjectRepositoryFolders
    {
        /// <summary>
        /// The HọcLiệuSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("824fbfaa-15d7-4bfd-9f08-6d137806f73a")]
        public partial class HọcLiệuSachMềmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _linkloginInfo;
            RepoItemInfo _lớp6Info;
            RepoItemInfo _tiếnganh6tập1sachbaitậpInfo;
            RepoItemInfo _giaobaitapInfo;
            RepoItemInfo _ngaygiobatdauInfo;
            RepoItemInfo _taobuttonInfo;
            RepoItemInfo _reportInfo;
            RepoItemInfo _quitInfo;
            RepoItemInfo _hourInfo;
            RepoItemInfo _reporerrorforhourInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềm  folder.
            /// </summary>
            public HọcLiệuSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềm", "/dom[@domain='hoclieu.sachmem.vn']", parentFolder, 30000, null, false, "824fbfaa-15d7-4bfd-9f08-6d137806f73a", "")
            {
                _linkloginInfo = new RepoItemInfo(this, "LinkLogin", ".//a[#'link-login']", 30000, null, "bab02dc8-19fa-4483-8623-aa4417b1c7d4");
                _lớp6Info = new RepoItemInfo(this, "Lớp6", ".//a[@innertext='Lớp 6']", 30000, null, "36b89ae8-b12f-4ee3-9f09-db05b4ac9686");
                _tiếnganh6tập1sachbaitậpInfo = new RepoItemInfo(this, "TiếngAnh6Tập1SachBaiTập", ".//a[@innertext='Tiếng Anh 6 Tập 1 Sách bài tập']", 30000, null, "9e581c03-ff62-4e52-9c97-1325a942d545");
                _giaobaitapInfo = new RepoItemInfo(this, "giaobaitap", ".//span[@innertext='Giao bài tập']", 30000, null, "fa6a2aa5-211e-4a83-8d2d-3723af2ed193");
                _ngaygiobatdauInfo = new RepoItemInfo(this, "Ngaygiobatdau", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b190848150cd8b9065dd1/5b99d4eaf327edcb8068f4ad/preview']/div[1]/div[10]/?/?/input[@type='text']", 30000, null, "6eced3d8-15cb-44dd-8d28-42285775221d");
                _taobuttonInfo = new RepoItemInfo(this, "TaoButton", ".//input[@value='Tạo']", 30000, null, "d9760cb7-eae9-4a1b-b941-bd8b24491b6e");
                _reportInfo = new RepoItemInfo(this, "Report", ".//div[@innertext=' Thời gian bắt đầu lớn hơn thời gian kết thúc ']", 30000, null, "ba18ae8f-096c-460a-905c-3facc0e845e2");
                _quitInfo = new RepoItemInfo(this, "Quit", ".//span[@innertext='×']", 30000, null, "8566fd14-a884-4812-9abe-fccb2c3a3f92");
                _hourInfo = new RepoItemInfo(this, "Hour", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b190848150cd8b9065dd1/5b99d4eaf327edcb8068f4ad/preview']/div[1]/div[10]/div[2]//table/tbody/tr[2]/?/?/input[@type='text']", 30000, null, "6711c161-6fa1-4721-9df9-1306ab19d68d");
                _reporerrorforhourInfo = new RepoItemInfo(this, "ReporErrorForHour", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/question_set/5a4b190848150cd8b9065dd1/5b99d4eaf327edcb8068f4ad/preview']/div[1]/div[10]/?/?/div[@innertext~'^Trường\\ này\\ không\\ được\\ để\\ ']", 30000, null, "7c03fcc7-39b2-4591-95da-4816ef5ea7af");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("824fbfaa-15d7-4bfd-9f08-6d137806f73a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("824fbfaa-15d7-4bfd-9f08-6d137806f73a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LinkLogin item.
            /// </summary>
            [RepositoryItem("bab02dc8-19fa-4483-8623-aa4417b1c7d4")]
            public virtual Ranorex.ATag LinkLogin
            {
                get
                {
                    return _linkloginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LinkLogin item info.
            /// </summary>
            [RepositoryItemInfo("bab02dc8-19fa-4483-8623-aa4417b1c7d4")]
            public virtual RepoItemInfo LinkLoginInfo
            {
                get
                {
                    return _linkloginInfo;
                }
            }

            /// <summary>
            /// The Lớp6 item.
            /// </summary>
            [RepositoryItem("36b89ae8-b12f-4ee3-9f09-db05b4ac9686")]
            public virtual Ranorex.ATag Lớp6
            {
                get
                {
                    return _lớp6Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Lớp6 item info.
            /// </summary>
            [RepositoryItemInfo("36b89ae8-b12f-4ee3-9f09-db05b4ac9686")]
            public virtual RepoItemInfo Lớp6Info
            {
                get
                {
                    return _lớp6Info;
                }
            }

            /// <summary>
            /// The TiếngAnh6Tập1SachBaiTập item.
            /// </summary>
            [RepositoryItem("9e581c03-ff62-4e52-9c97-1325a942d545")]
            public virtual Ranorex.ATag TiếngAnh6Tập1SachBaiTập
            {
                get
                {
                    return _tiếnganh6tập1sachbaitậpInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TiếngAnh6Tập1SachBaiTập item info.
            /// </summary>
            [RepositoryItemInfo("9e581c03-ff62-4e52-9c97-1325a942d545")]
            public virtual RepoItemInfo TiếngAnh6Tập1SachBaiTậpInfo
            {
                get
                {
                    return _tiếnganh6tập1sachbaitậpInfo;
                }
            }

            /// <summary>
            /// The giaobaitap item.
            /// </summary>
            [RepositoryItem("fa6a2aa5-211e-4a83-8d2d-3723af2ed193")]
            public virtual Ranorex.SpanTag giaobaitap
            {
                get
                {
                    return _giaobaitapInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The giaobaitap item info.
            /// </summary>
            [RepositoryItemInfo("fa6a2aa5-211e-4a83-8d2d-3723af2ed193")]
            public virtual RepoItemInfo giaobaitapInfo
            {
                get
                {
                    return _giaobaitapInfo;
                }
            }

            /// <summary>
            /// The Ngaygiobatdau item.
            /// </summary>
            [RepositoryItem("6eced3d8-15cb-44dd-8d28-42285775221d")]
            public virtual Ranorex.InputTag Ngaygiobatdau
            {
                get
                {
                    return _ngaygiobatdauInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Ngaygiobatdau item info.
            /// </summary>
            [RepositoryItemInfo("6eced3d8-15cb-44dd-8d28-42285775221d")]
            public virtual RepoItemInfo NgaygiobatdauInfo
            {
                get
                {
                    return _ngaygiobatdauInfo;
                }
            }

            /// <summary>
            /// The TaoButton item.
            /// </summary>
            [RepositoryItem("d9760cb7-eae9-4a1b-b941-bd8b24491b6e")]
            public virtual Ranorex.InputTag TaoButton
            {
                get
                {
                    return _taobuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TaoButton item info.
            /// </summary>
            [RepositoryItemInfo("d9760cb7-eae9-4a1b-b941-bd8b24491b6e")]
            public virtual RepoItemInfo TaoButtonInfo
            {
                get
                {
                    return _taobuttonInfo;
                }
            }

            /// <summary>
            /// The Report item.
            /// </summary>
            [RepositoryItem("ba18ae8f-096c-460a-905c-3facc0e845e2")]
            public virtual Ranorex.DivTag Report
            {
                get
                {
                    return _reportInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Report item info.
            /// </summary>
            [RepositoryItemInfo("ba18ae8f-096c-460a-905c-3facc0e845e2")]
            public virtual RepoItemInfo ReportInfo
            {
                get
                {
                    return _reportInfo;
                }
            }

            /// <summary>
            /// The Quit item.
            /// </summary>
            [RepositoryItem("8566fd14-a884-4812-9abe-fccb2c3a3f92")]
            public virtual Ranorex.SpanTag Quit
            {
                get
                {
                    return _quitInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Quit item info.
            /// </summary>
            [RepositoryItemInfo("8566fd14-a884-4812-9abe-fccb2c3a3f92")]
            public virtual RepoItemInfo QuitInfo
            {
                get
                {
                    return _quitInfo;
                }
            }

            /// <summary>
            /// The Hour item.
            /// </summary>
            [RepositoryItem("6711c161-6fa1-4721-9df9-1306ab19d68d")]
            public virtual Ranorex.InputTag Hour
            {
                get
                {
                    return _hourInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Hour item info.
            /// </summary>
            [RepositoryItemInfo("6711c161-6fa1-4721-9df9-1306ab19d68d")]
            public virtual RepoItemInfo HourInfo
            {
                get
                {
                    return _hourInfo;
                }
            }

            /// <summary>
            /// The ReporErrorForHour item.
            /// </summary>
            [RepositoryItem("7c03fcc7-39b2-4591-95da-4816ef5ea7af")]
            public virtual Ranorex.DivTag ReporErrorForHour
            {
                get
                {
                    return _reporerrorforhourInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ReporErrorForHour item info.
            /// </summary>
            [RepositoryItemInfo("7c03fcc7-39b2-4591-95da-4816ef5ea7af")]
            public virtual RepoItemInfo ReporErrorForHourInfo
            {
                get
                {
                    return _reporerrorforhourInfo;
                }
            }
        }

        /// <summary>
        /// The ĐăngNhậpSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("7ee862ee-d4ef-4165-b63a-15aaab7bcaad")]
        public partial class ĐăngNhậpSachMềmAppFolder : RepoGenBaseFolder
        {
            AutomationTestProjectRepositoryFolders.BodyFolder _body;

            /// <summary>
            /// Creates a new ĐăngNhậpSachMềm  folder.
            /// </summary>
            public ĐăngNhậpSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ĐăngNhậpSachMềm", "/dom[@domain='accounts.sachmem.vn']", parentFolder, 30000, null, false, "7ee862ee-d4ef-4165-b63a-15aaab7bcaad", "")
            {
                _body = new AutomationTestProjectRepositoryFolders.BodyFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ee862ee-d4ef-4165-b63a-15aaab7bcaad")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ee862ee-d4ef-4165-b63a-15aaab7bcaad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Body folder.
            /// </summary>
            [RepositoryFolder("dec70314-15a1-4bd7-988d-b92f1b7f776a")]
            public virtual AutomationTestProjectRepositoryFolders.BodyFolder Body
            {
                get { return _body; }
            }
        }

        /// <summary>
        /// The BodyFolder folder.
        /// </summary>
        [RepositoryFolder("dec70314-15a1-4bd7-988d-b92f1b7f776a")]
        public partial class BodyFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _commitInfo;

            /// <summary>
            /// Creates a new Body  folder.
            /// </summary>
            public BodyFolder(RepoGenBaseFolder parentFolder) :
                    base("Body", "", parentFolder, 30000, null, false, "dec70314-15a1-4bd7-988d-b92f1b7f776a", "")
            {
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[@id='user_email']", 30000, null, "5c6fc1d1-6483-48c6-9ccd-4410ee2b75e8");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[@id='user_password']", 30000, null, "1bdfdc75-8cfa-4882-83c1-acff05c14f3c");
                _commitInfo = new RepoItemInfo(this, "Commit", ".//input[@name='commit']", 30000, null, "1f678280-1cf1-49e7-83fa-7a19e2508110");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dec70314-15a1-4bd7-988d-b92f1b7f776a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dec70314-15a1-4bd7-988d-b92f1b7f776a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("5c6fc1d1-6483-48c6-9ccd-4410ee2b75e8")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("5c6fc1d1-6483-48c6-9ccd-4410ee2b75e8")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("1bdfdc75-8cfa-4882-83c1-acff05c14f3c")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("1bdfdc75-8cfa-4882-83c1-acff05c14f3c")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Commit item.
            /// </summary>
            [RepositoryItem("1f678280-1cf1-49e7-83fa-7a19e2508110")]
            public virtual Ranorex.InputTag Commit
            {
                get
                {
                    return _commitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Commit item info.
            /// </summary>
            [RepositoryItemInfo("1f678280-1cf1-49e7-83fa-7a19e2508110")]
            public virtual RepoItemInfo CommitInfo
            {
                get
                {
                    return _commitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}